[project]
name = "rag"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
    "fire",
    "bm25s",
    "flake8",
    "mypy"
]

[tool.uv]
package = false

[tool.mypy]
exclude = ["vllm/"]

[[tool.mypy.overrides]]
module = "fire.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["bm25s", "bm25s.*"]
ignore_missing_imports = true