[project]
name = "rag"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
    "fire",
    "bm25s",
    "torch",
    "transformers",
    "tqdm",
    "flake8",
    "mypy"
]

[tool.uv]
package = false

[tool.uv.sources]
torch = {index = "pytorch-cpu"}

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.mypy]
plugins = ["pydantic.mypy"]
exclude = ["data/", "rag/", ".venv/"]

[[tool.mypy.overrides]]
module = ["fire.*", "bm25s", "bm25s.*",
    "transformers", "transformers.*",
    "torch", "torch.*", "tqdm"]
ignore_missing_imports = true
follow_imports = "skip"